openapi: '3.0.2'
info:
  title: Grader Extension API
  description: The REST API for grader server extension
  license:
    name: BSD-3-Clause
  version: '0.1.4'
servers:
  - url: /services/mock
    description: relative path to mock

###### Tags of API endpoints
tags:
  - name: "Lectures"
    description: "Available lectures"
  - name: "Assignments"
    description: Assignments of a lecture
  - name: "Submissions"
    description: View submissions of an assignment
  - name: "Grading"
    description: Manage the grading and feedback of assignments (Instructor)
  - name: "Permissions"
    description: Endpoint for security scopes of user
  - name: "Version Control"
    description: Working with git repositories

paths:
  /lectures:
    $ref: './paths_shared.yml#/lectures'

  /lectures/{lect_id}:
    $ref: './paths_shared.yml#/lecturesById'

  /lectures/{lect_id}/users:
    $ref: './paths_shared.yml#/lectureUsers'

  /lectures/{lect_id}/assignments:
    $ref: './paths_shared.yml#/assignments'

  /lectures/{lect_id}/assignments/{a_id}:
    $ref: './paths_shared.yml#/assignmentsById'

  /lectures/{lect_id}/assignments/{a_id}/submissions:
    $ref: './paths_extension.yml#/submissions'

  /lectures/{lect_id}/assignments/{a_id}/submissions/{s_id}:
    $ref: './paths_shared.yml#/submissionsById'

  /lectures/{lect_id}/assignments/{a_id}/submissions/{s_id}/properties:
    $ref: './paths_grader.yml#/propertiesSubmission'

  /lectures/{lect_id}/assignments/{a_id}/grading/{s_id}/auto:
    $ref: './paths_shared.yml#/auto'

  /lectures/{lect_id}/assignments/{a_id}/grading/{s_id}/feedback:
    $ref: './paths_shared.yml#/feedback'

  /permissions:
    $ref: './paths_shared.yml#/permissions'

  /lectures/{lect_id}/assignments/{a_id}/pull/{repo}:
    $ref: './paths_extension.yml#/versionControlPull'

  /lectures/{lect_id}/assignments/{a_id}/push/{repo}:
    $ref: './paths_extension.yml#/versionControlPush'

  /lectures/{lect_id}/assignments/{a_id}/log/{repo}:
    $ref: './paths_extension.yml#/gitLog'

  /lectures/{lect_id}/assignments/{a_id}/generate:
    $ref: './paths_extension.yml#/generate'

  /lectures/{lect_id}/assignments/{a_id}/remote-status/{repo}:
    $ref: './paths_extension.yml#/remoteStatus'

components:
  securitySchemes:
    hub_auth:
      type: apiKey
      in: header
      name: Token