# Default values for grader-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: ghcr.io/tu-wien-datalab/grader-service
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  #tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: "grader-service"

serviceAccount:
  # Specifies whether a service account should be created or not
  create: true
  # Annotations to add to the service account
  annotations: {}

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 4010
port: 4010

jupyterhub:
  apiUrl: http://hub:8081/hub/api
  baseUrl: /

db:
  dialect: sqlite
  host: /var/lib/grader-service/grader.db

gitConfig:
  gitUser: "grader-service"
  gitEmail: "grader-service@mail.com"

volumePermissions:
  enabled: true

autogradeExecutorClass: KubeAutogradeExecutor
kubeAutogradeExecutor:
  image: ghcr.io/tu-wien-datalab/grader-service-labextension
  tag: latest
  extraVolumes: ""
  extraVolumeMounts: ""

requestHandlerConfig:
  enable_lti_features: false
  lti_client_id: ""
  lti_token_url: ""
  lti_username_convert: ""
  lti_token_private_key: ""


# pvc
storageClassName: ""
accessMode: "ReadWriteMany"
capacity: "10G"
volume: ""

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
