
# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.8"
    nodejs: "16"

# Build documentation in the docs/ directory with Sphinx
sphinx:
  builder: html
  configuration: ./docs/source/conf.py
  fail_on_warning: true

# Build documentation with MkDocs
#mkdocs:
#  configuration: mkdocs.yml

# Optionally set the version of Python and requirements required to build your docs
#python:
#  install:
#    - requirements: ./requirements-docs.txt
#    - requirements: ./grader_convert/requirements.txt
#    - requirements: ./grader_service/requirements.txt
#    - path: grader_convert
#      method: setuptools
#    - path: grader_service
#      method: setuptools
#    - path: grader_labextension
#      method: pip