FROM ubuntu:focal

RUN apt-get update &&\
    apt-get install -yq --no-install-recommends \
    python3 \
    python3-pip \
    curl \
    vim \
    iputils-ping \
    git && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# node and npm
RUN curl -fsSL https://deb.nodesource.com/setup_lts.x | bash - && \
    apt-get install -y nodejs
RUN apt-get install -y build-essential

# Install Jupyterhub
RUN npm install -g configurable-http-proxy
RUN python3 -m pip install jupyterhub
RUN python3 -m pip install --upgrade notebook

# INSTALL grader-service
COPY ./grading_labextension /grading_labextension

# install grading service
RUN python3 -m pip install -r /grading_labextension/requirements.txt && \
    python3 -m pip install  /grading_labextension && \
    rm -rf /grading_labextension

RUN useradd -m -s /bin/bash -N -u 1000 jovyan
RUN echo "jovyan:jupyter" | chpasswd

COPY ./jupyterhub_labextension_config.py /jupyterhub_labextension_config.py

ENTRYPOINT ["jupyterhub", "-f", "/jupyterhub_labextension_config.py"]