service:
  type: ClusterIP
  port: 4010
port: 4010
jupyterhub:
  apiUrl: http://proxy-public/hub/api
  baseUrl: /

image:
  repository: matthiasmatt/grader-service
  pullPolicy: Never
  tag: latest

db:
  dialect: postgresql
  url: "postgresql://grader-service:Starfish@grader-db-postgresql.jupyter.svc.cluster.local:5432"

gitConfig:
  gitUser: "grader-service"
  gitEmail: "grader-service@mail.com"

volumePermissions:
  enabled: true

concurrentGradingTasks: 1
autogradeExecutorClass: KubeAutogradeExecutor
kubeAutogradeExecutor:
  image: ghcr.io/tu-wien-datalab/grader-service-labextension

# pvc
# If storageClassName is not defined or commented as below, the default storageClass from your cluster will be used.

#storageClassName: "csi-cinder-sc-delete"
accessMode: "ReadWriteOnce"
capacity: "5G"

ingress:
  enabled: true

rabbitmq:
  resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: 500m
        memory: 1Gi

