service:
  type: ClusterIP
  port: 4010
port: 4010
jupyterhub:
  apiUrl: http://proxy-public/hub/api
  baseUrl: /

db:
  dialect: sqlite
  host: /var/lib/grader-service/grader.db

gitConfig:
  gitUser: "grader-service"
  gitEmail: "grader-service@mail.com"

volumePermissions:
  enabled: true

autogradeExecutorClass: LocalAutogradeExecutor #KubeAutogradeExecutor

# pvc
# If storageClassName is not defined or commented as below, the default storageClass from your cluster will be used.

#storageClassName: "csi-cinder-sc-delete"
accessMode: "ReadWriteOnce"
capacity: "5G"

ingress:
  enabled: false
