# Copyright (c) 2022, TU Wien
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

version: "2.2"
services:

  jupyterlab:
    build:
      context: .
      dockerfile: Dockerfile_lab
    image: "grader-lap:latest"
    ports:
      - "8000:8000"
    depends_on:
      - grader_service
    volumes:
        # used instead of COPY inside Dockerfile
        # COPY ./jupyterhub_labextension_config.py /jupyterhub_labextension_config.py
        # makes it easier to change the values.
      - ./jupyterhub_labextension_config.py:/jupyterhub_labextension_config.py

  grader_service:
    build:
      context: .
      dockerfile: Dockerfile_service
    image: "grader_service:latest"
    ports:
      - "4010:4010"
    volumes:
        # used instead of COPY inside Dockerfile
        # COPY ./grader_service_config.py /var/lib/grader-service/grader_service_config.py
        # makes it easier to change the values.
      - ./grader_service_config.py:/var/lib/grader-service/grader_service_config.py
