hub:
  extraConfig:
    config.py: |
      c.Authenticator.admin_users = {'fjaeger','matthiasmatt'}
      c.JupyterHub.load_groups = {
      "20wle2__instructor": ["matthiasmatt", "fjaeger"],
      "21wle1__instructor": ["matthiasmatt", "fjaeger"],
      "22sle3__student": ["matthiasmatt", "fjaeger"]
      }
      
  services:
    grader:
      url: "http://grader-service:4010"
      oauth_client_id: "grader"
singleuser:
  defaultUrl: "/lab"
  image:
    name: s210.dl.hpc.tuwien.ac.at/grader/grader-notebook-minimal
    tag: latest
    # pullPolicy: Always
  extraEnv:
    GRADER_HOST_URL: "grader-service"
