"""initial

Revision ID: a1791b1371ed
Revises: 
Create Date: 2021-05-05 11:42:24.126371

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql.schema import UniqueConstraint


# revision identifiers, used by Alembic.
revision = 'a1791b1371ed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lecture',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('semester', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=True),
    sa.Column('state', sa.Enum('inactive', 'active', 'complete'), nullable=False),
    sa.Column('deleted', sa.Enum('active', 'deleted'),server_default='active', nullable=False),

    sa.PrimaryKeyConstraint('id'),
    UniqueConstraint('name', 'semester', name='u_sem_name')
    )
    op.create_table('user',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('assignment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('lectid', sa.Integer(), nullable=True),
    sa.Column('duedate', sa.DateTime(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('created', 'released', 'fetching', 'fetched', 'complete'), nullable=True),
    sa.Column('deleted', sa.Enum('active', 'deleted'), server_default='active', nullable=False),

    sa.ForeignKeyConstraint(['lectid'], ['lecture.id'], ),
    sa.PrimaryKeyConstraint('id'),
    )
    op.create_table('takepart',
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('lectid', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['lectid'], ['lecture.id'], ),
    sa.ForeignKeyConstraint(['username'], ['user.name'], ),
    sa.PrimaryKeyConstraint('username', 'lectid')
    )
    op.create_table('file',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('assignid', sa.Integer(), nullable=True),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('exercise', sa.Boolean(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assignid'], ['assignment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('submission',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('submitting', 'not_graded', 'automatically_graded', 'manually_graded'), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('assignid', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['assignid'], ['assignment.id'], ),
    sa.ForeignKeyConstraint(['username'], ['user.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('submission')
    op.drop_table('file')
    op.drop_table('takepart')
    op.drop_table('assignment')
    op.drop_table('user')
    op.drop_table('lecture')
    # ### end Alembic commands ###
