"""changed takepart

Revision ID: ad148ce37d25
Revises: 128484503600
Create Date: 2021-05-07 10:20:08.068744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad148ce37d25'
down_revision = '128484503600'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('takepart', schema=None) as batch_op:
        batch_op.alter_column('lectid',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('takepart', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('lectid',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
