"""changed takepart-table

Revision ID: cd9d9a6f4563
Revises: ad148ce37d25
Create Date: 2021-05-07 11:32:33.692727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd9d9a6f4563'
down_revision = 'ad148ce37d25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
