FROM postgres

# Install python
RUN apt-get update && \
    apt-get install -y python3 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Install uv
COPY --from=ghcr.io/astral-sh/uv:0.9.3 /uv /uvx /bin/

WORKDIR /app

# Install python dependencies, only copying necessary files
COPY ./pyproject.toml MANIFEST.in ./
RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --no-dev

# Copy the project files and install the package itself
COPY ./grader_service ./grader_service
RUN --mount=type=cache,target=/root/.cache/uv \
    uv pip install .

CMD ["sh", "-c", "/app/init-db-postgres.sh"]
