FROM python:3.13-slim

# Install git and sqlite
RUN apt-get update && \
    apt-get install -y git sqlite3 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Install uv
COPY --from=ghcr.io/astral-sh/uv:0.9.3 /uv /uvx /bin/
ENV UV_SYSTEM_PYTHON=true

WORKDIR /app

# Install python dependencies, only copying necessary files
COPY ./pyproject.toml MANIFEST.in ./
RUN uv pip compile pyproject.toml -o requirements.txt
RUN --mount=type=cache,target=/root/.cache/uv \
    uv pip install -r requirements.txt && \
    uv pip install numpy ipykernel

# Copy the project files and install the package itself
COPY ./grader_service ./grader_service
RUN --mount=type=cache,target=/root/.cache/uv \
    uv pip install .

# Set default branch to main and default user
RUN git config --global init.defaultBranch main && \
    git config --global user.name "Your Name" && \
    git config --global user.email "youremail@example.com"

WORKDIR /app/service_dir
EXPOSE 4010

CMD ["grader-service", "-f", "/app/grader_service_config.py"]
