FROM python:3.10-slim-buster

# Install git
RUN apt-get update && \
    apt-get install -y git && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copy necessary files and folders
COPY ./grader_service ./grader_service
COPY ./examples/docker_compose/grader_service_config.py ./grader_service_config.py

RUN pip install ./grader_service/

# Set default branch to main and default user
RUN git config --global init.defaultBranch main && \
    git config --global user.name "Your Name" && \
    git config --global user.email "youremail@example.com"

# Create new databse
RUN grader-service-migrate

EXPOSE 4010

ENTRYPOINT ["grader-service", "-f", "/app/grader_service_config.py"]
