FROM python:3.10-slim-buster

# Install git
RUN apt-get update && \
    apt-get install -y git && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app


COPY /examples/docker_compose/jupyterhub_config.py ./jupyterhub_config.py

RUN pip install grader_labextension

RUN python3 -m pip install jupyterhub configurable-http-proxy dockerspawner jupyterlab

# Create a dedicated user for JupyterHub
RUN useradd -m jupyterhubuser

# Change ownership so that the non-root user can access it
RUN chown -R jupyterhubuser:jupyterhubuser /app
RUN mkdir /data && chown -R jupyterhubuser:jupyterhubuser /data

# Switch to the jupyterhub user
USER jupyterhubuser

ENTRYPOINT ["jupyterhub", "-f", "/app/jupyterhub_config.py"]