FROM python:3.13-slim

# Install git
RUN apt-get update && \
    apt-get install -y git && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copy necessary files and folders
COPY ./pyproject.toml MANIFEST.in ./
COPY ./grader_service ./grader_service

RUN pip install .

# Set default branch to main and default user
RUN git config --global init.defaultBranch main && \
    git config --global user.name "Your Name" && \
    git config --global user.email "youremail@example.com"

# Create new databse
WORKDIR /app/service_dir
RUN grader-service-migrate
EXPOSE 4010

CMD ["grader-service", "-f", "/app/grader_service_config.py"]
