apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "grader-service.fullname" . }}-worker
  labels:
    {{- include "grader-service.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.workers.replication }}
  selector:
    matchLabels:
      {{- include "grader-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- if or .Values.podAnnotations .Values.workers.podAnnotations }}
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.workers.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      labels:
        {{- include "grader-service.selectorLabels" . | nindent 8 }}
        hub.jupyter.org/network-access-hub: "true"
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.workers.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "grader-service.serviceAccountName" . }}
      securityContext:
        {{- if .Values.workers.podSecurityContext }}
        {{- toYaml .Values.workers.podSecurityContext | nindent 8 }}
        {{- else }}
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}-worker
          securityContext:
            {{- if .Values.workers.securityContext }}
            {{- toYaml .Values.workers.securityContext | nindent 12 }}
            {{- else }}
            {{- toYaml .Values.securityContext | nindent 12 }}
            {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: [ "grader-worker" ]
          args: [ "-f", "/etc/grader-service/grader_service_config.py" ]
          resources:
            {{- toYaml .Values.workers.resources | nindent 12 }}
          env:
            {{- include "grader-service.extraEnv" .Values.extraEnv | nindent 12 }}
            {{- include "grader-service.extraEnv" .Values.workers.extraEnv | nindent 12 }}
            {{- include "grader-service.dbEnv" . | nindent 12 }}
            {{- include "grader-service.ltiEnv" . | nindent 12 }}
            {{- include "grader-service.rabbitmqEnv" . | nindent 12 }}
            - name: GRADER_PORT
              value: {{ .Values.port | quote }}
          {{- $envFrom := concat (.Values.extraEnvFrom | default list) (.Values.workers.extraEnvFrom | default list) }}
          {{- with $envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/grader-service
{{- if .Values.subPath }}
              subPath: {{ .Values.subPath }}
{{- end }}
            - name: config
              mountPath: /etc/grader-service/grader_service_config.py
              subPath: grader_service_config.py
            - name: config
              mountPath: /var/lib/grader-service/.gitconfig
              subPath: .gitconfig
      volumes:
        - name: data
{{- if .Values.hostpath }}
          hostPath:
            path: {{ .Values.hostpath }}
            type: DirectoryOrCreate
{{- else }}
          persistentVolumeClaim:
            claimName: grader-service
            readOnly: false
{{- end }}
        - name: config
          configMap:
            defaultMode: 444
            name: grader-service

      {{- with (.Values.workers.nodeSelector | default .Values.nodeSelector) }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (.Values.workers.affinity | default .Values.affinity) }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (.Values.workers.tolerations | default .Values.tolerations) }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
