apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: grader-service
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
        - ""
    resources:
      - pods
      - pods/status
      - pods/log
    verbs: ["get", "create", "update", "delete"]