
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "grader-service.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "grader-service.labels" . | nindent 4 }}
data:
{{ if eq .Values.autogradeExecutorClass "KubeAutogradeExecutor" }}
  grader_service_config.py: |
    from grader_service.autograding.kube.kube_grader import KubeAutogradeExecutor
    c.RequestHandlerConfig.autograde_executor_class = KubeAutogradeExecutor
    c.KubeAutogradeExecutor.kube_context = None
{{- if .Values.kubeAutogradeExecutor.namespace }}
    c.KubeAutogradeExecutor.namespace = {{ .Values.kubeAutogradeExecutor.namespace | quote }}
{{- end }}
    c.KubeAutogradeExecutor.base_input_path = "/var/lib/grader-service/convert_in"
    c.KubeAutogradeExecutor.base_output_path = "/var/lib/grader-service/convert_out"
    c.KubeAutogradeExecutor.default_image_name = lambda l, a: "{{ .Values.kubeAutogradeExecutor.image }}:{{ .Values.kubeAutogradeExecutor.tag | default .Chart.AppVersion }}"
    c.KubeAutogradeExecutor.volume_mounts = [{"name": "data",{{- if .Values.subPath }} "subPath": "{{ .Values.subPath }}/convert_in",{{- end -}} "mountPath": "/var/lib/grader-service/convert_in"},
    {"name": "data",{{- if .Values.subPath }} "subPath": "{{ .Values.subPath }}/convert_out",{{- end -}} "mountPath": "/var/lib/grader-service/convert_in"}]
    c.KubeAutogradeExecutor.volumes = [{"name": "data", "persistentVolumeClaim": {"claimName": "{{ include "grader-service.fullname" . }}"}}]
{{ else }}
  grader_service_config.py: |
    from grader_service.autograding.local_grader import LocalAutogradeExecutor
    c.RequestHandlerConfig.autograde_executor_class = LocalAutogradeExecutor
{{ end }}

  .gitconfig: |
    [user]
      name = {{ .Values.gitConfig.gitUser }}
      email = {{ .Values.gitConfig.gitEmail }}
