apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: grader-service
  namespace: {{ .Release.Namespace }}
spec:
  egress:
  - ports:
    - port: 8081
      protocol: TCP
    to:
    - namespaceSelector: {}
    - podSelector:
        matchLabels:
          app: jupyterhub
          component: hub
  - to:
    - namespaceSelector: {}
    - podSelector:
          matchLabels:
            app: jupyterhub
            component: singleuser-server
  - ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
    - port: 6443
      protocol: TCP
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
        - 169.254.169.254/32
  ingress:
    - from:
      - namespaceSelector: {}
      - podSelector:
          matchLabels:
            app: jupyterhub
            component: hub
      - podSelector:
          matchLabels:
            app: jupyterhub
            component: singleuser-server
      ports:
        - port: 4010
          protocol: TCP
  podSelector:
    matchLabels:
      app.kubernetes.io/name: grader-service
  policyTypes:
    - Ingress
    - Egress
---