{{ if and .Values.volumePermissions.enabled (.Capabilities.APIVersions.Has "policy/v1beta1") (eq .Capabilities.KubeVersion.Major "1") (lt .Capabilities.KubeVersion.Minor "25") }}
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: { .Release.Name }-grader-run-as-root-psp
spec:
  allowPrivilegeEscalation: false
  fsGroup:
    ranges:
    - max: 65535
      min: 1000
    rule: MustRunAs
  requiredDropCapabilities:
  - ALL
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    ranges:
    - max: 65535
      min: 1
    rule: MustRunAs
  volumes:
  - configMap
  - emptyDir
  - projected
  - secret
  - downwardAPI
  - csi
  - persistentVolumeClaim
  - ephemeral

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: { .Release.Name }-grader-run-as-root-psp
rules:
- apiGroups:
  - policy
  resourceNames:
  - grader-run-as-root-psp
  resources:
  - podsecuritypolicies
  verbs:
  - use

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: { .Release.Name }-psp:binding:grader-run-as-root-psp
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: grader-run-as-root-psp
subjects:
  - kind: ServiceAccount
    name: {{ include "grader-service.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}

{{ end }}
