apiVersion: v1
kind: Secret
metadata:
  name: grader-service
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  hub.services.grader.apiToken: {{ default "" .Values.jupyterhub.apiToken | b64enc | quote }}
