# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from api.models.base_model_ import Model
from api.models.manual_grading_content_feedback_cells import ManualGradingContentFeedbackCells
from api import util

from api.models.manual_grading_content_feedback_cells import ManualGradingContentFeedbackCells  # noqa: E501

class ManualGradingContent(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, feedback_cells=None):  # noqa: E501
        """ManualGradingContent - a model defined in OpenAPI

        :param id: The id of this ManualGradingContent.  # noqa: E501
        :type id: int
        :param feedback_cells: The feedback_cells of this ManualGradingContent.  # noqa: E501
        :type feedback_cells: List[ManualGradingContentFeedbackCells]
        """
        self.openapi_types = {
            'id': int,
            'feedback_cells': List[ManualGradingContentFeedbackCells]
        }

        self.attribute_map = {
            'id': 'id',
            'feedback_cells': 'feedback_cells'
        }

        self._id = id
        self._feedback_cells = feedback_cells

    @classmethod
    def from_dict(cls, dikt) -> 'ManualGradingContent':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ManualGradingContent of this ManualGradingContent.  # noqa: E501
        :rtype: ManualGradingContent
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this ManualGradingContent.


        :return: The id of this ManualGradingContent.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ManualGradingContent.


        :param id: The id of this ManualGradingContent.
        :type id: int
        """

        self._id = id

    @property
    def feedback_cells(self):
        """Gets the feedback_cells of this ManualGradingContent.


        :return: The feedback_cells of this ManualGradingContent.
        :rtype: List[ManualGradingContentFeedbackCells]
        """
        return self._feedback_cells

    @feedback_cells.setter
    def feedback_cells(self, feedback_cells):
        """Sets the feedback_cells of this ManualGradingContent.


        :param feedback_cells: The feedback_cells of this ManualGradingContent.
        :type feedback_cells: List[ManualGradingContentFeedbackCells]
        """

        self._feedback_cells = feedback_cells
