# coding: utf-8

# flake8: noqa
from __future__ import absolute_import
# import models into model package
from swagger_server.models.assignment import Assignment
from swagger_server.models.assignment_file import AssignmentFile
from swagger_server.models.error_message import ErrorMessage
from swagger_server.models.exercise import Exercise
from swagger_server.models.feedback import Feedback
from swagger_server.models.grading_result import GradingResult
from swagger_server.models.inline_response200 import InlineResponse200
from swagger_server.models.inline_response2001 import InlineResponse2001
from swagger_server.models.inline_response2001_data import InlineResponse2001Data
from swagger_server.models.inline_response2001_submissions import InlineResponse2001Submissions
from swagger_server.models.lecture import Lecture
from swagger_server.models.manual_grading_content import ManualGradingContent
from swagger_server.models.manual_grading_content_feedback_cells import ManualGradingContentFeedbackCells
from swagger_server.models.submission import Submission
from swagger_server.models.user import User
from swagger_server.models.validation_result import ValidationResult
from swagger_server.models.validation_result_validation_errors import ValidationResultValidationErrors
