# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.inline_response2001_data import InlineResponse2001Data  # noqa: F401,E501
from swagger_server import util


class InlineResponse2001(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, n_submissions: int=None, data: List[InlineResponse2001Data]=None):  # noqa: E501
        """InlineResponse2001 - a model defined in Swagger

        :param n_submissions: The n_submissions of this InlineResponse2001.  # noqa: E501
        :type n_submissions: int
        :param data: The data of this InlineResponse2001.  # noqa: E501
        :type data: List[InlineResponse2001Data]
        """
        self.swagger_types = {
            'n_submissions': int,
            'data': List[InlineResponse2001Data]
        }

        self.attribute_map = {
            'n_submissions': 'n_submissions',
            'data': 'data'
        }
        self._n_submissions = n_submissions
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2001':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_1 of this InlineResponse2001.  # noqa: E501
        :rtype: InlineResponse2001
        """
        return util.deserialize_model(dikt, cls)

    @property
    def n_submissions(self) -> int:
        """Gets the n_submissions of this InlineResponse2001.


        :return: The n_submissions of this InlineResponse2001.
        :rtype: int
        """
        return self._n_submissions

    @n_submissions.setter
    def n_submissions(self, n_submissions: int):
        """Sets the n_submissions of this InlineResponse2001.


        :param n_submissions: The n_submissions of this InlineResponse2001.
        :type n_submissions: int
        """

        self._n_submissions = n_submissions

    @property
    def data(self) -> List[InlineResponse2001Data]:
        """Gets the data of this InlineResponse2001.


        :return: The data of this InlineResponse2001.
        :rtype: List[InlineResponse2001Data]
        """
        return self._data

    @data.setter
    def data(self, data: List[InlineResponse2001Data]):
        """Sets the data of this InlineResponse2001.


        :param data: The data of this InlineResponse2001.
        :type data: List[InlineResponse2001Data]
        """

        self._data = data
