# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.inline_response2001_submissions import InlineResponse2001Submissions  # noqa: F401,E501
from swagger_server.models.user import User  # noqa: F401,E501
from swagger_server import util


class InlineResponse2001Data(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, student: User=None, submissions: List[InlineResponse2001Submissions]=None):  # noqa: E501
        """InlineResponse2001Data - a model defined in Swagger

        :param student: The student of this InlineResponse2001Data.  # noqa: E501
        :type student: User
        :param submissions: The submissions of this InlineResponse2001Data.  # noqa: E501
        :type submissions: List[InlineResponse2001Submissions]
        """
        self.swagger_types = {
            'student': User,
            'submissions': List[InlineResponse2001Submissions]
        }

        self.attribute_map = {
            'student': 'student',
            'submissions': 'submissions'
        }
        self._student = student
        self._submissions = submissions

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2001Data':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_1_data of this InlineResponse2001Data.  # noqa: E501
        :rtype: InlineResponse2001Data
        """
        return util.deserialize_model(dikt, cls)

    @property
    def student(self) -> User:
        """Gets the student of this InlineResponse2001Data.


        :return: The student of this InlineResponse2001Data.
        :rtype: User
        """
        return self._student

    @student.setter
    def student(self, student: User):
        """Sets the student of this InlineResponse2001Data.


        :param student: The student of this InlineResponse2001Data.
        :type student: User
        """

        self._student = student

    @property
    def submissions(self) -> List[InlineResponse2001Submissions]:
        """Gets the submissions of this InlineResponse2001Data.


        :return: The submissions of this InlineResponse2001Data.
        :rtype: List[InlineResponse2001Submissions]
        """
        return self._submissions

    @submissions.setter
    def submissions(self, submissions: List[InlineResponse2001Submissions]):
        """Sets the submissions of this InlineResponse2001Data.


        :param submissions: The submissions of this InlineResponse2001Data.
        :type submissions: List[InlineResponse2001Submissions]
        """

        self._submissions = submissions
