# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.assignment import Assignment  # noqa: F401,E501
from swagger_server.models.submission import Submission  # noqa: F401,E501
from swagger_server import util


class InlineResponse200(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, assignment: Assignment=None, submissions: List[Submission]=None):  # noqa: E501
        """InlineResponse200 - a model defined in Swagger

        :param assignment: The assignment of this InlineResponse200.  # noqa: E501
        :type assignment: Assignment
        :param submissions: The submissions of this InlineResponse200.  # noqa: E501
        :type submissions: List[Submission]
        """
        self.swagger_types = {
            'assignment': Assignment,
            'submissions': List[Submission]
        }

        self.attribute_map = {
            'assignment': 'assignment',
            'submissions': 'submissions'
        }
        self._assignment = assignment
        self._submissions = submissions

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200 of this InlineResponse200.  # noqa: E501
        :rtype: InlineResponse200
        """
        return util.deserialize_model(dikt, cls)

    @property
    def assignment(self) -> Assignment:
        """Gets the assignment of this InlineResponse200.


        :return: The assignment of this InlineResponse200.
        :rtype: Assignment
        """
        return self._assignment

    @assignment.setter
    def assignment(self, assignment: Assignment):
        """Sets the assignment of this InlineResponse200.


        :param assignment: The assignment of this InlineResponse200.
        :type assignment: Assignment
        """

        self._assignment = assignment

    @property
    def submissions(self) -> List[Submission]:
        """Gets the submissions of this InlineResponse200.


        :return: The submissions of this InlineResponse200.
        :rtype: List[Submission]
        """
        return self._submissions

    @submissions.setter
    def submissions(self, submissions: List[Submission]):
        """Sets the submissions of this InlineResponse200.


        :param submissions: The submissions of this InlineResponse200.
        :type submissions: List[Submission]
        """

        self._submissions = submissions
