# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.grading_result import GradingResult  # noqa: F401,E501
from swagger_server.models.submission import Submission  # noqa: F401,E501
from swagger_server import util


class InlineResponse2001Submissions(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, submission: Submission=None, grading_result: GradingResult=None):  # noqa: E501
        """InlineResponse2001Submissions - a model defined in Swagger

        :param submission: The submission of this InlineResponse2001Submissions.  # noqa: E501
        :type submission: Submission
        :param grading_result: The grading_result of this InlineResponse2001Submissions.  # noqa: E501
        :type grading_result: GradingResult
        """
        self.swagger_types = {
            'submission': Submission,
            'grading_result': GradingResult
        }

        self.attribute_map = {
            'submission': 'submission',
            'grading_result': 'grading_result'
        }
        self._submission = submission
        self._grading_result = grading_result

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2001Submissions':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_1_submissions of this InlineResponse2001Submissions.  # noqa: E501
        :rtype: InlineResponse2001Submissions
        """
        return util.deserialize_model(dikt, cls)

    @property
    def submission(self) -> Submission:
        """Gets the submission of this InlineResponse2001Submissions.


        :return: The submission of this InlineResponse2001Submissions.
        :rtype: Submission
        """
        return self._submission

    @submission.setter
    def submission(self, submission: Submission):
        """Sets the submission of this InlineResponse2001Submissions.


        :param submission: The submission of this InlineResponse2001Submissions.
        :type submission: Submission
        """

        self._submission = submission

    @property
    def grading_result(self) -> GradingResult:
        """Gets the grading_result of this InlineResponse2001Submissions.


        :return: The grading_result of this InlineResponse2001Submissions.
        :rtype: GradingResult
        """
        return self._grading_result

    @grading_result.setter
    def grading_result(self, grading_result: GradingResult):
        """Sets the grading_result of this InlineResponse2001Submissions.


        :param grading_result: The grading_result of this InlineResponse2001Submissions.
        :type grading_result: GradingResult
        """

        self._grading_result = grading_result
