// tslint:disable
/**
 * Grader Server Extension API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    AssignmentFile,
    Exercise,
} from './';

/**
 * @export
 * @interface Assignment
 */
export interface Assignment {
    /**
     * @type {number}
     * @memberof Assignment
     */
    id?: number;
    /**
     * @type {string}
     * @memberof Assignment
     */
    name?: string;
    /**
     * @type {Array<Exercise>}
     * @memberof Assignment
     */
    exercises?: Array<Exercise>;
    /**
     * @type {Array<AssignmentFile>}
     * @memberof Assignment
     */
    files?: Array<AssignmentFile>;
    /**
     * @type {string}
     * @memberof Assignment
     */
    due_date?: string;
    /**
     * @type {string}
     * @memberof Assignment
     */
    path?: string;
    /**
     * @type {string}
     * @memberof Assignment
     */
    status?: AssignmentStatusEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum AssignmentStatusEnum {
    Created = 'created',
    Released = 'released',
    Fetched = 'fetched',
    Submitted = 'submitted',
    Complete = 'complete'
}

