// tslint:disable
/**
 * Grader Server Extension API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface Exercise
 */
export interface Exercise {
    /**
     * @type {number}
     * @memberof Exercise
     */
    id?: number;
    /**
     * @type {number}
     * @memberof Exercise
     */
    a_id?: number;
    /**
     * @type {string}
     * @memberof Exercise
     */
    name?: string;
    /**
     * @type {string}
     * @memberof Exercise
     */
    ex_type?: ExerciseExTypeEnum;
    /**
     * @type {number}
     * @memberof Exercise
     */
    points?: number;
}

/**
 * @export
 * @enum {string}
 */
export enum ExerciseExTypeEnum {
    Nbgrader = 'nbgrader'
}

