// tslint:disable
/**
 * Grader Server Extension API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface Feedback
 */
export interface Feedback {
    /**
     * @type {number}
     * @memberof Feedback
     */
    id?: number;
    /**
     * @type {number}
     * @memberof Feedback
     */
    submission_id?: number;
    /**
     * @type {string}
     * @memberof Feedback
     */
    path?: string;
}
