// tslint:disable
/**
 * Grader Server Extension API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface GradingResult
 */
export interface GradingResult {
    /**
     * @type {number}
     * @memberof GradingResult
     */
    id?: number;
    /**
     * @type {string}
     * @memberof GradingResult
     */
    status?: GradingResultStatusEnum;
    /**
     * @type {number}
     * @memberof GradingResult
     */
    autograde_score?: number;
    /**
     * @type {number}
     * @memberof GradingResult
     */
    total_score?: number;
}

/**
 * @export
 * @enum {string}
 */
export enum GradingResultStatusEnum {
    NeedsAutoGrading = 'needs_auto_grading',
    NeedsManualGrading = 'needs_manual_grading',
    Completed = 'completed'
}

