// tslint:disable
/**
 * Grader Server Extension API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    Assignment,
    Submission,
} from './';

/**
 * @export
 * @interface InlineResponse200
 */
export interface InlineResponse200 {
    /**
     * @type {Assignment}
     * @memberof InlineResponse200
     */
    assignment?: Assignment;
    /**
     * @type {Array<Submission>}
     * @memberof InlineResponse200
     */
    submissions?: Array<Submission>;
}
