// tslint:disable
/**
 * Grader Server Extension API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    InlineResponse2001Data,
} from './';

/**
 * @export
 * @interface InlineResponse2001
 */
export interface InlineResponse2001 {
    /**
     * @type {number}
     * @memberof InlineResponse2001
     */
    n_submissions?: number;
    /**
     * @type {Array<InlineResponse2001Data>}
     * @memberof InlineResponse2001
     */
    data?: Array<InlineResponse2001Data>;
}
