// tslint:disable
/**
 * Grader Server Extension API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface Lecture
 */
export interface Lecture {
    /**
     * @type {number}
     * @memberof Lecture
     */
    id?: number;
    /**
     * @type {string}
     * @memberof Lecture
     */
    name?: string;
    /**
     * @type {string}
     * @memberof Lecture
     */
    code?: string;
    /**
     * @type {boolean}
     * @memberof Lecture
     */
    complete?: boolean;
    /**
     * @type {string}
     * @memberof Lecture
     */
    semester?: string;
}
