// tslint:disable
/**
 * Grader Server Extension API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface Submission
 */
export interface Submission {
    /**
     * @type {number}
     * @memberof Submission
     */
    id?: number;
    /**
     * @type {string}
     * @memberof Submission
     */
    submitted_at?: string;
    /**
     * @type {string}
     * @memberof Submission
     */
    status?: SubmissionStatusEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum SubmissionStatusEnum {
    NotGraded = 'not_graded',
    AutomaticallyGraded = 'automatically_graded',
    ManuallyGraded = 'manually_graded'
}

