// tslint:disable
/**
 * Grader Server Extension API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface User
 */
export interface User {
    /**
     * @type {string}
     * @memberof User
     */
    id?: string;
    /**
     * @type {string}
     * @memberof User
     */
    name?: string;
}
