// tslint:disable
/**
 * Grader Server Extension API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    ValidationResultValidationErrors,
} from './';

/**
 * @export
 * @interface ValidationResult
 */
export interface ValidationResult {
    /**
     * @type {string}
     * @memberof ValidationResult
     */
    status?: ValidationResultStatusEnum;
    /**
     * @type {Array<ValidationResultValidationErrors>}
     * @memberof ValidationResult
     */
    validation_errors?: Array<ValidationResultValidationErrors>;
}

/**
 * @export
 * @enum {string}
 */
export enum ValidationResultStatusEnum {
    Passed = 'passed',
    Failed = 'failed'
}

