# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from grader.grading_labextension.models.base_model_ import Model
from grader.grading_labextension.models.inline_response200_data import InlineResponse200Data
from grader.grading_labextension import util

from grader.grading_labextension.models.inline_response200_data import InlineResponse200Data  # noqa: E501

class InlineResponse200(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, n_submissions=None, data=None):  # noqa: E501
        """InlineResponse200 - a model defined in OpenAPI

        :param n_submissions: The n_submissions of this InlineResponse200.  # noqa: E501
        :type n_submissions: int
        :param data: The data of this InlineResponse200.  # noqa: E501
        :type data: List[InlineResponse200Data]
        """
        self.openapi_types = {
            'n_submissions': int,
            'data': List[InlineResponse200Data]
        }

        self.attribute_map = {
            'n_submissions': 'n_submissions',
            'data': 'data'
        }

        self._n_submissions = n_submissions
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200 of this InlineResponse200.  # noqa: E501
        :rtype: InlineResponse200
        """
        return util.deserialize_model(dikt, cls)

    @property
    def n_submissions(self):
        """Gets the n_submissions of this InlineResponse200.


        :return: The n_submissions of this InlineResponse200.
        :rtype: int
        """
        return self._n_submissions

    @n_submissions.setter
    def n_submissions(self, n_submissions):
        """Sets the n_submissions of this InlineResponse200.


        :param n_submissions: The n_submissions of this InlineResponse200.
        :type n_submissions: int
        """

        self._n_submissions = n_submissions

    @property
    def data(self):
        """Gets the data of this InlineResponse200.


        :return: The data of this InlineResponse200.
        :rtype: List[InlineResponse200Data]
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this InlineResponse200.


        :param data: The data of this InlineResponse200.
        :type data: List[InlineResponse200Data]
        """

        self._data = data
