/**
 * Grader Server Extension API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AssignmentFile } from './assignmentFile';
import { Exercise } from './exercise';


export interface Assignment { 
    id?: number;
    name?: string;
    exercises?: Array<Exercise>;
    files?: Array<AssignmentFile>;
    due_date?: string;
    path?: string;
    status?: Assignment.StatusEnum;
}
export namespace Assignment {
    export type StatusEnum = 'created' | 'released' | 'fetched' | 'submitted' | 'complete';
    export const StatusEnum = {
        Created: 'created' as StatusEnum,
        Released: 'released' as StatusEnum,
        Fetched: 'fetched' as StatusEnum,
        Submitted: 'submitted' as StatusEnum,
        Complete: 'complete' as StatusEnum
    };
}


