/**
 * Grader Extension API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Exercise { 
    id?: number;
    a_id?: number;
    name?: string;
    ex_type?: Exercise.ExTypeEnum;
    points?: number;
    hashcode?: string;
    path?: string;
}
export namespace Exercise {
    export type ExTypeEnum = 'nbgrader';
    export const ExTypeEnum = {
        Nbgrader: 'nbgrader' as ExTypeEnum
    };
}


