/**
 * Grader Extension API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GradingResult { 
    id?: number;
    status?: GradingResult.StatusEnum;
    autograde_score?: number;
    total_score?: number;
}
export namespace GradingResult {
    export type StatusEnum = 'needs_auto_grading' | 'needs_manual_grading' | 'completed';
    export const StatusEnum = {
        NeedsAutoGrading: 'needs_auto_grading' as StatusEnum,
        NeedsManualGrading: 'needs_manual_grading' as StatusEnum,
        Completed: 'completed' as StatusEnum
    };
}


