/**
 * Grader Server Extension API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InlineResponse200Data } from './inlineResponse200Data';


export interface InlineResponse200 { 
    n_submissions?: number;
    data?: Array<InlineResponse200Data>;
}

