/**
 * Grader Server Extension API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InlineResponse2001Submissions } from './inlineResponse2001Submissions';
import { User } from './user';


export interface InlineResponse2001Data { 
    student?: User;
    submissions?: Array<InlineResponse2001Submissions>;
}

