/**
 * Grader Extension API Schemas
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Submission { 
    id?: number;
    submitted_at?: string;
    auto_status?: Submission.Auto_StatusEnum;
    manual_status?: Submission.Manual_StatusEnum;
    score?: number;
    commit_hash?: string;
}
export namespace Submission {
    export type Auto_StatusEnum = 'not_graded' | 'automatically_graded' | 'pending';
    export type Manual_StatusEnum = 'not_graded' | 'manually_graded';
    export const Auto_StatusEnum = {
        NotGraded: 'not_graded' as Auto_StatusEnum,
        AutomaticallyGraded: 'automatically_graded' as Auto_StatusEnum,
        ManuallyGraded: 'pending' as Auto_StatusEnum
    };
    export const Manual_StatusEnum = {
        NotGraded: 'not_graded' as Manual_StatusEnum,
        ManuallyGraded: 'manually_graded' as Manual_StatusEnum
    };
}



