/**
 * Grader Extension API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Submission { 
    id?: number;
    submitted_at?: string;
    status?: Submission.StatusEnum;
}
export namespace Submission {
    export type StatusEnum = 'submitting' | 'not_graded' | 'automatically_graded' | 'manually_graded';
    export const StatusEnum = {
        Submitting: 'submitting' as StatusEnum,
        NotGraded: 'not_graded' as StatusEnum,
        AutomaticallyGraded: 'automatically_graded' as StatusEnum,
        ManuallyGraded: 'manually_graded' as StatusEnum
    };
}


