/**
 * Grader Server Extension API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ValidationResultValidationErrors } from './validationResultValidationErrors';


export interface ValidationResult { 
    status?: ValidationResult.StatusEnum;
    validation_errors?: Array<ValidationResultValidationErrors>;
}
export namespace ValidationResult {
    export type StatusEnum = 'passed' | 'failed';
    export const StatusEnum = {
        Passed: 'passed' as StatusEnum,
        Failed: 'failed' as StatusEnum
    };
}


