# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build Labextension

on:
  workflow_call:

permissions:
  contents: read

jobs:
  update-version:
    if: ${{ !startsWith(github.ref, 'refs/tags/grader-labextension') }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install tbump
      run: |
        python -m pip install --upgrade pip
        pip install tbump

    - name: Bump Version
      working-directory: ./grader_labextension
      env:
        current-version: ${{ echo "$(tbump current-version)" }}
        commit-hash: ${{ echo "::set-output name=hash::$(git rev-parse --short HEAD)" }}
      run: tbump $current_version-$commit_hash --non-interactive --only-patch
      

  build:
    if: ${{ always() }}
    needs: update-version
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
    - name: Install build dependencies
      working-directory: ./grader_labextension
      run: |
        python -m pip install --upgrade pip
        pip install jupyter_packaging~=0.12.0 jupyterlab~=3.1 packaging setuptools twine build
    - name: Install dependencies
      working-directory: ./grader_labextension
      run: |
        python -m pip install --upgrade pip
        pip install build wheel twine
        pip install -r ../grader_convert/requirements.txt
        pip install -r requirements.txt
    - name: Build package
      working-directory: ./grader_labextension
      run: python -m build -n

    # Upload Artifacts
    - name: Archive labextension artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist-labextension
        retention-days: 1
        path: |
          grader_labextension/dist
          !grader_labextension/dist/**/*.md