name: Build Labextension

on:
  workflow_call:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1

      - name: Install uv
        uses: astral-sh/setup-uv@c18668ad3cf93ea998bef934396af7bb5c839dc7  # v10.2.0
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install

      - name: Set up Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020  # v7.0.0

      - name: Install the project
        run: uv sync --locked --dev

      - name: Install npm dependencies
        working-directory: packages/labextension
        run: uv run jlpm

      - name: Build extension
        working-directory: packages/labextension
        run: uv run jlpm build:prod

      - name: Build package
        run: uv build --package grader-labextension --out-dir packages/labextension/dist

      - name: Run ruff check
        run: uv run ruff check packages/labextension

      - name: Upload artifact
        uses: actions/upload-artifact@cf430e030ddbb5b0abf93d22962f4752f3646cd9  # v7.0.2
        with:
          name: dist-labextension
          path: packages/labextension/dist/
