
name: "Project Management Actions"

on:
  issues:
    types:
      - opened
      - reopened

jobs:
  send_issue_to_management_tool:
    runs-on: ubuntu-latest
    steps:
      - name: View issue information
        env:
          TITLE: ${{ github.event.issue.title }}
          BODY: ${{ github.event.issue.body }}
        run: |
          echo "Issue title: $TITLE"
          echo "Issue body: $BODY"

      - name: Send issue to GitLab CI
        env:
          TITLE: ${{ github.event.issue.title }}
          BODY: ${{ github.event.issue.body }}
        run: |
          curl -X POST --fail \
               -F token=${{ secrets.GITLAB_CI_TRIGGER_TOKEN }} \
               -F "ref=main" \
               -F "variables[TITLE]=$TITLE" \
               -F "variables[DESCRIPTION]=$BODY" \
               -F "variables[SOURCE]=github" \
               ${{ secrets.GITLAB_CI_TRIGGER_URL }}